### ISSUE TITLE
Sidekiq replacement

### ISSUE THREAD

**Issue by Skeyelab** [shiroyasha/kamisama#3]
Is this intended to replace Sidekiq?  Or replace the 2nd worker process used w Sidekiq?

**Comment by shiroyasha** [comment]
Probably not. Sidekiq is a great software, for event based processing.

However, sometimes you need to run your own background workers that poll your application for changes, or you want to implement a custom RabbitMQ worker, or Kafka worker, or some kind of job scheduler....

In those cases, kamisama offers a simple way to run multiple independent processes.
